### ISSUE TITLE
Implement Bind V2

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_BIND#61]
Implement Bind V2 by cloning repo and modifying where needed in Dockerfile

**Comment by dappnodedev** [comment]
The Bind V2 will forward all the DNS requests to the Docker DNS server, so that we just need to handle docker aliases in order to provide proper DNS resolution to the user

We need to clone the https://github.com/DNSCrypt/dnscrypt-proxy repo inside the Dockerfile and modify some files in order to adapt the software to Dappnode needs
